name: singbox

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update:
    extends:
      - ./.github/workflows/workflow.yml#request
      - run: python singbox/run.py
      - ./.github/workflows/workflow.yml#push
