name: singbox

on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        id: step1
      - uses: actions/setup-python@v4
        id: step2
        with:
          python-version: 3.x
          architecture: x64
      - run: pip install requests
        id: step3
        needs: step2
      - run: python singbox/bootstrap.py
        id: step4
        needs: [step1, step3]
      - run: |
          git config --local user.name "Sean"
          git config --local user.email "sxfmao@163.com"
          git add .
          git commit -m "commit"
          git push
        needs: step4
