name: singbox

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          architecture: x64
      - run: pip install requests
      - run: python singbox/build.py
      - run: ls singbox/mobile
      - run: |
          git config user.name "${{ vars.GIT_NAME }}"
          git config user.email "${{ vars.GIT_EMAIL }}"
      - run: |
          git add -A
          if ! git diff --exit-code --cached; then
            git commit -m "Update singbox."
            echo -e "\033[0;33m========== changed ==========\033[0m"
            echo "isChange=true" > output.env
          else
            echo -e "\033[0;33m========== unchanged ==========\033[0m"
            echo "isChange=false" > output.env
          fi
        id: check
      - run: git push
        if: ${{ env.isChange == 'true' }}
