name: singbox

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          architecture: x64
      - run: pip install requests
      - run: python singbox/bootstrap.py
      - run: |
          git config user.name "${{ vars.GIT_NAME }}"
          git config user.email "${{ vars.GIT_EMAIL }}"
      - run: |
          if ! git diff --exit-code --cached; then
            git add .
            git commit -m "commit"
            echo "::set-output name=isChange::true"
          else
            echo "::set-output name=isChange::false"
          fi
        id: check
      - run: git push
        if: steps.check.outputs.isChange == 'true'
